using System.Text;
using System.Web;

namespace WebCrapApp
{
    public static class StringExtensions
    {
        public static Uri AddQuery(this Uri uri, string name, string value)
        {
            var httpValueCollection = HttpUtility.ParseQueryString(uri.Query);

            httpValueCollection.Remove(name);
            httpValueCollection.Add(name, value);

            UriBuilder ub = new(uri);

            // this code block is taken from httpValueCollection.ToString() method
            // and modified so it encodes strings with HttpUtility.UrlEncode
            if (httpValueCollection.Count == 0)
                ub.Query = string.Empty;
            else
            {
                var sb = new StringBuilder();

                for (int i = 0; i < httpValueCollection.Count; i++)
                {
                    string? text = httpValueCollection.GetKey(i);
                    {
                        text = HttpUtility.UrlEncode(text);

                        string val = (text != null) ? (text + "=") : string.Empty;
                        string[]? vals = httpValueCollection.GetValues(i);

                        if (sb.Length > 0)
                        {
                            sb.Append('&');
                        }

                        if (vals == null || vals.Length == 0)
                        {
                            sb.Append(val);
                        }
                        else
                        {
                            if (vals.Length == 1)
                            {
                                sb.Append(val);
                                sb.Append(HttpUtility.UrlEncode(vals[0]));
                            }
                            else
                            {
                                for (int j = 0; j < vals.Length; j++)
                                {
                                    if (j > 0)
                                    {
                                        sb.Append('&');
                                    }
                                    sb.Append(val);
                                    sb.Append(HttpUtility.UrlEncode(vals[j]));
                                }
                            }
                        }
                    }
                }

                ub.Query = sb.ToString();
            }
            return ub.Uri;
        }

        public static string GetCountryCode(string CountryName)
        {
            Dictionary<string, string> param = new()
            {
                //{ "United States", "US" },
                //{ "United Kingdom", "UK" },
                //{ "Germany", "DE" },
                //{ "Italy", "IT" },
                //{ "Spain", "ES" },
                //{ "France", "FR" },
                //{ "Australia", "AU" },
                //{ "Japan", "JP" },
                //{ "India", "IN" },
                {"Afghanistan", "AFG" },
                {"Aruba", "ABW" },
                {"Angola", "AGO" },
                {"Anguila", "AIA" },
                {"Albania", "ALB" },
                {"Åland Islands", "ALI" },
                {"Andorra", "AND" },
                {"Netherlands Antilles", "ANT" },
                {"United Arab Emirates", "ARE" },
                {"Argentina", "ARG" },
                {"Armenia", "ARM" },
                {"American Samoa", "ASM" },
                {"Antarctica", "ATA" },
                {"Fr. So. Ant. Tr", "ATF" },
                {"Antigua and Barbuda", "ATG" },
                {"Australia", "AUS" },
                {"Austria", "AUT" },
                {"Azerbaijan", "AZE" },
                {"Br. Antr. Terr", "BAT" },
                {"Burundi", "BDI" },
                {"Belgium", "BEL" },
                {"Benin", "BEN" },
                {"Burkina Faso", "BFA" },
                {"Bangladesh", "BGD" },
                {"Bulgaria", "BGR" },
                {"Bahrain", "BHR" },
                {"Bahamas, The", "BHS" },
                {"Bosnia and Herzegovina", "BIH" },
                {"Belarus", "BLR" },
                {"Belgium-Luxembourg", "BLX" },
                {"Belize", "BLZ" },
                {"Bermuda", "BMU" },
                {"Bolivia", "BOL" },
                {"Brazil", "BRA" },
                {"Barbados", "BRB" },
                {"Brunei", "BRN" },
                {"Bhutan", "BTN" },
                {"Bunkers", "BUN" },
                {"Bouvet Island", "BVT" },
                {"Botswana", "BWA" },
                {"Central African Republic", "CAF" },
                {"Canada", "CAN" },
                {"Cocos (Keeling) Islands", "CCK" },
                {"Switzerland", "CHE" },
                {"Chile", "CHL" },
                {"China", "CHN" },
                {"Cote d'Ivoire", "CIV" },
                {"Cameroon", "CMR" },
                {"Congo, Rep.", "COG" },
                {"Cook Islands", "COK" },
                {"Colombia", "COL" },
                {"Comoros", "COM" },
                {"Cape Verde", "CPV" },
                {"Costa Rica", "CRI" },
                {"Czechoslovakia", "CSK" },
                {"Cuba", "CUB" },
                {"Christmas Island", "CXR" },
                {"Cayman Islands", "CYM" },
                {"Cyprus", "CYP" },
                {"Czech Republic", "CZE" },
                {"German Democratic Republic", "DDR" },
                {"Germany", "DEU" },
                {"Djibouti", "DJI" },
                {"Dominica", "DMA" },
                {"Denmark", "DNK" },
                {"Dominican Republic", "DOM" },
                {"Algeria", "DZA" },
                {"Ecuador", "ECU" },
                {"Egypt, Arab Rep.", "EGY" },
                {"Eritrea", "ERI" },
                {"Western Sahara", "ESH" },
                {"Spain", "ESP" },
                {"Estonia", "EST" },
                {"Ethiopia(includes Eritrea)", "ETF" },
                {"Ethiopia(excludes Eritrea)", "ETH" },
                {"European Union", "EUN" },
                {"Finland", "FIN" },
                {"Fiji", "FJI" },
                {"Falkland Island", "FLK" },
                {"France", "FRA" },
                {"Free Zones", "FRE" },
                {"Faeroe Islands", "FRO" },
                {"Micronesia, Fed. Sts.", "FSM" },
                {"Gabon", "GAB" },
                {"Gaza Strip", "GAZ" },
                {"United Kingdom", "GBR" },
                {"Georgia", "GEO" },
                {"Ghana", "GHA" },
                {"Gibraltar", "GIB" },
                {"Guinea", "GIN" },
                {"Guadeloupe", "GLP" },
                {"Gambia, The", "GMB" },
                {"Guinea-Bissau", "GNB" },
                {"Equatorial Guinea", "GNQ" },
                {"Greece", "GRC" },
                {"Grenada", "GRD" },
                {"Greenland", "GRL" },
                {"Guatemala", "GTM" },
                {"French Guiana", "GUF" },
                {"Guam", "GUM" },
                {"Guyana", "GUY" },
                {"Hong Kong, China", "HKG" },
                {"Heard Island and McDonald Isla", "HMD" },
                {"Honduras", "HND" },
                {"Croatia", "HRV" },
                {"Haiti", "HTI" },
                {"Hungary", "HUN" },
                {"Indonesia", "IDN" },
                {"India", "IND" },
                {"British Indian Ocean Ter.", "IOT" },
                {"Ireland", "IRL" },
                {"Iran, Islamic Rep.", "IRN" },
                {"Iraq", "IRQ" },
                {"Iceland", "ISL" },
                {"Israel", "ISR" },
                {"Italy", "ITA" },
                {"Jamaica", "JAM" },
                {"Jordan", "JOR" },
                {"Japan", "JPN" },
                {"Jhonston Island", "JTN" },
                {"Kazakhstan", "KAZ" },
                {"Kenya", "KEN" },
                {"Kyrgyz Republic", "KGZ" },
                {"Cambodia", "KHM" },
                {"Kiribati", "KIR" },
                {"Saint Kitts-Nevis-Anguilla-Aru", "KN1" },
                {"St. Kitts and Nevis", "KNA" },
                {"Korea, Rep.", "KOR" },
                {"Kosovo", "KSV" },
                {"Kuwait", "KWT" },
                {"Lao PDR", "LAO" },
                {"Lebanon", "LBN" },
                {"Liberia", "LBR" },
                {"Libya", "LBY" },
                {"St. Lucia", "LCA" },
                {"Liechtenstein", "LIE" },
                {"Sri Lanka", "LKA" },
                {"Lesotho", "LSO" },
                {"Lithuania", "LTU" },
                {"Luxembourg", "LUX" },
                {"Latvia", "LVA" },
                {"Macao", "MAC" },
                {"Morocco", "MAR" },
                {"Monaco", "MCO" },
                {"Moldova", "MDA" },
                {"Madagascar", "MDG" },
                {"Maldives", "MDV" },
                {"Mexico", "MEX" },
                {"Marshall Islands", "MHL" },
                {"Midway Islands", "MID" },
                {"Macedonia, FYR", "MKD" },
                {"Mali", "MLI" },
                {"Malta", "MLT" },
                {"Myanmar", "MNR" },
                {"Mongolia", "MNG" },
                {"Northern Mariana Islands", "MNP" },
                {"Montenegro", "MNT" },
                {"Mozambique", "MOZ" },
                {"Mauritania", "MRT" },
                {"Montserrat", "MSR" },
                {"Martinique", "MTQ" },
                {"Mauritius", "MUS" },
                {"Malawi", "MWI" },
                {"Malaysia", "MYS" },
                {"Mayotte", "MYT" },
                {"Namibia", "NAM" },
                {"New Caledonia", "NCL" },
                {"Niger", "NER" },
                {"Norfolk Island", "NFK" },
                {"Nigeria", "NGA" },
                {"Nicaragua", "NIC" },
                {"Niue", "NIU" },
                {"Netherlands", "NLD" },
                {"Norway", "NOR" },
                {"Nepal", "NPL" },
                {"Nauru", "NRU" },
                {"Neutral Zone", "NZE" },
                {"New Zealand", "NZL" },
                {"Oman", "OMN" },
                {"Pakistan", "PAK" },
                {"Panama", "PAN" },
                {"Pacific Islands", "PCE" },
                {"Pitcairn", "PCN" },
                {"Fm Panama Cz", "PCZ" },
                {"Peru", "PER" },
                {"Philippines", "PHL" },
                {"Palau", "PLW" },
                {"Pen Malaysia", "PMY" },
                {"Papua New Guinea", "PNG" },
                {"Poland", "POL" },
                {"Puerto Rico", "PRI" },
                {"Korea, Dem. Rep.", "PRK" },
                {"Portugal", "PRT" },
                {"Paraguay", "PRY" },
                {"Occ.Pal.Terr", "PSE" },
                {"French Polynesia", "PYF" },
                {"Qatar", "QAT" },
                {"Reunion", "REU" },
                {"Romania", "ROM" },
                {"Russian Federation", "RUS" },
                {"Rwanda", "RWA" },
                {"Ryukyu Is", "RYU" },
                {"Saudi Arabia", "SAU" },
                {"Sabah", "SBH" },
                {"Sudan", "SDN" },
                {"Senegal", "SEN" },
                {"Yugoslavia", "SER" },
                {"Singapore", "SGP" },
                {"South Georgia and the South Sa", "SGS" },
                {"Saint Helena", "SHN" },
                {"SIKKIM", "SIK" },
                {"Svalbard and Jan Mayen Is", "SJM" },
                {"Solomon Islands", "SLB" },
                {"Sierra Leone", "SLE" },
                {"El Salvador", "SLV" },
                {"San Marino", "SMR" },
                {"Somalia", "SOM" },
                {"Special Categories", "SPE" },
                {"Saint Pierre and Miquelon", "SPM" },
                {"Sao Tome and Principe", "STP" },
                {"Suriname", "SUR" },
                {"Slovak Republic", "SVK" },
                {"Slovenia", "SVN" },
                {"Fm Vietnam Rp", "SVR" },
                {"Soviet Union", "SVU" },
                {"Sweden", "SWE" },
                {"Sarawak", "SWK" },
                {"Swaziland", "SWZ" },
                {"Seychelles", "SYC" },
                {"Syrian Arab Republic", "SYR" },
                {"Fm Tanganyik", "TAN" },
                {"Turks and Caicos Isl.", "TCA" },
                {"Chad", "TCD" },
                {"Togo", "TGO" },
                {"Thailand", "THA" },
                {"Tajikistan", "TJK" },
                {"Tokelau", "TKL" },
                {"Turkmenistan", "TKM" },
                {"East Timor", "TMP" },
                {"Tonga", "TON" },
                {"Trinidad and Tobago", "TTO" },
                {"Tunisia", "TUN" },
                {"Turkey", "TUR" },
                {"Tuvalu", "TUV" },
                {"Taiwan, China", "TWN" },
                {"Tanzania", "TZA" },
                {"Uganda", "UGA" },
                {"Ukraine", "UKR" },
                {"United States Minor Outlying I", "UMI" },
                {"Unspecified", "UNS" },
                {"Uruguay", "URY" },
                {"United States", "USA" },
                {"Us Msc.Pac.I", "USP" },
                {"Uzbekistan", "UZB" },
                {"Holy See", "VAT" },
                {"St. Vincent and the Grenadines", "VCT" },
                {"Fm Vietnam DR", "VDR" },
                {"Venezuela", "VEN" },
                {"British Virgin Islands", "VGB" },
                {"Virgin Islands (U.S.)", "VIR" },
                {"Vietnam", "VNM" },
                {"Vanuatu", "VUT" },
                {"Wake Island", "WAK" },
                {" World", "WLD" },
                {"Wallis and Futura Isl.", "WLF" },
                {"Samoa", "WSM" },
                {"Yemen Democratic", "YDR" },
                {"Yemen", "YEM" },
                {"Yugoslavia, FR (Serbia/Montene", "YUG" },
                {"South Africa", "ZAF" },
                {"Congo, Dem. Rep.", "ZAR" },
                {"Zambia", "ZMB" },
                {"Fm Zanz-Pemb", "ZPM" },
                {"Fm Rhod Nyas", "ZW1" },
                {"Zimbabwe", "ZWE" },
            };
            var result = param.Where(x => x.Key == CountryName).Select(x => x.Value).FirstOrDefault();
            return result != null ? result : "";
        }

        public static string GetCategoryName(int CategoryCode)
        {
            Dictionary<string, string> param = new()
            {
                { "All categories", "0" },
                { "Arts & Entertainment", "1" },
                { "Autos & Vehicles", "2" },
                { "Beauty & Fitness", "3" },
                { "Books & Literature", "4" },
                { "Business & Industrial", "5" },
                { "Computers & Electronics", "6" },
                { "Finance", "7" },
                { "Food & Drink", "8" },
                { "Games", "9" },
                { "Health", "10" },
                { "Hobbies & Leisure", "11" },
                { "Home & Garden", "12" },
                { "Internet & Telecom", "13" },
                { "Jobs & Education", "14" },
                { "Law & Government", "15" },
                { "News", "16" },
                { "Online Communities", "17" },
                { "People & Society", "18" },
                { "Pets & Animals", "19" },
                { "Real Estate", "20" },
                { "Reference", "21" },
                { "Science", "22" },
                { "Shopping", "23" },
                { "Sports", "24" },
                { "Travel", "25" }
            };
            var result = param.Where(x => x.Value == CategoryCode.ToString()).Select(x => x.Key).FirstOrDefault();
            return result != null ? result : "";
        }

        public static Dictionary<string, string> GetCategories()
        {
            Dictionary<string, string> param = new()
            {
                { "All categories", "0" },
                { "Arts & Entertainment", "1" },
                { "Autos & Vehicles", "2" },
                { "Beauty & Fitness", "3" },
                { "Books & Literature", "4" },
                { "Business & Industrial", "5" },
                { "Computers & Electronics", "6" },
                { "Finance", "7" },
                { "Food & Drink", "8" },
                { "Games", "9" },
                { "Health", "10" },
                { "Hobbies & Leisure", "11" },
                { "Home & Garden", "12" },
                { "Internet & Telecom", "13" },
                { "Jobs & Education", "14" },
                { "Law & Government", "15" },
                { "News", "16" },
                { "Online Communities", "17" },
                { "People & Society", "18" },
                { "Pets & Animals", "19" },
                { "Real Estate", "20" },
                { "Reference", "21" },
                { "Science", "22" },
                { "Shopping", "23" },
                { "Sports", "24" },
                { "Travel", "25" }
            };
            return param;
        }

        public static Dictionary<string, string> GetAllCountryCode()
        {
            Dictionary<string, string> param = new()
            {
                {"Afghanistan", "AFG" },
                {"Aruba", "ABW" },
                {"Angola", "AGO" },
                {"Anguila", "AIA" },
                {"Albania", "ALB" },
                {"Åland Islands", "ALI" },
                {"Andorra", "AND" },
                {"Netherlands Antilles", "ANT" },
                {"United Arab Emirates", "ARE" },
                {"Argentina", "ARG" },
                {"Armenia", "ARM" },
                {"American Samoa", "ASM" },
                {"Antarctica", "ATA" },
                {"Fr. So. Ant. Tr", "ATF" },
                {"Antigua and Barbuda", "ATG" },
                {"Australia", "AUS" },
                {"Austria", "AUT" },
                {"Azerbaijan", "AZE" },
                {"Br. Antr. Terr", "BAT" },
                {"Burundi", "BDI" },
                {"Belgium", "BEL" },
                {"Benin", "BEN" },
                {"Burkina Faso", "BFA" },
                {"Bangladesh", "BGD" },
                {"Bulgaria", "BGR" },
                {"Bahrain", "BHR" },
                {"Bahamas, The", "BHS" },
                {"Bosnia and Herzegovina", "BIH" },
                {"Belarus", "BLR" },
                {"Belgium-Luxembourg", "BLX" },
                {"Belize", "BLZ" },
                {"Bermuda", "BMU" },
                {"Bolivia", "BOL" },
                {"Brazil", "BRA" },
                {"Barbados", "BRB" },
                {"Brunei", "BRN" },
                {"Bhutan", "BTN" },
                {"Bunkers", "BUN" },
                {"Bouvet Island", "BVT" },
                {"Botswana", "BWA" },
                {"Central African Republic", "CAF" },
                {"Canada", "CAN" },
                {"Cocos (Keeling) Islands", "CCK" },
                {"Switzerland", "CHE" },
                {"Chile", "CHL" },
                {"China", "CHN" },
                {"Cote d'Ivoire", "CIV" },
                {"Cameroon", "CMR" },
                {"Congo, Rep.", "COG" },
                {"Cook Islands", "COK" },
                {"Colombia", "COL" },
                {"Comoros", "COM" },
                {"Cape Verde", "CPV" },
                {"Costa Rica", "CRI" },
                {"Czechoslovakia", "CSK" },
                {"Cuba", "CUB" },
                {"Christmas Island", "CXR" },
                {"Cayman Islands", "CYM" },
                {"Cyprus", "CYP" },
                {"Czech Republic", "CZE" },
                {"German Democratic Republic", "DDR" },
                {"Germany", "DEU" },
                {"Djibouti", "DJI" },
                {"Dominica", "DMA" },
                {"Denmark", "DNK" },
                {"Dominican Republic", "DOM" },
                {"Algeria", "DZA" },
                {"Ecuador", "ECU" },
                {"Egypt, Arab Rep.", "EGY" },
                {"Eritrea", "ERI" },
                {"Western Sahara", "ESH" },
                {"Spain", "ESP" },
                {"Estonia", "EST" },
                {"Ethiopia(includes Eritrea)", "ETF" },
                {"Ethiopia(excludes Eritrea)", "ETH" },
                {"European Union", "EUN" },
                {"Finland", "FIN" },
                {"Fiji", "FJI" },
                {"Falkland Island", "FLK" },
                {"France", "FRA" },
                {"Free Zones", "FRE" },
                {"Faeroe Islands", "FRO" },
                {"Micronesia, Fed. Sts.", "FSM" },
                {"Gabon", "GAB" },
                {"Gaza Strip", "GAZ" },
                {"United Kingdom", "GBR" },
                {"Georgia", "GEO" },
                {"Ghana", "GHA" },
                {"Gibraltar", "GIB" },
                {"Guinea", "GIN" },
                {"Guadeloupe", "GLP" },
                {"Gambia, The", "GMB" },
                {"Guinea-Bissau", "GNB" },
                {"Equatorial Guinea", "GNQ" },
                {"Greece", "GRC" },
                {"Grenada", "GRD" },
                {"Greenland", "GRL" },
                {"Guatemala", "GTM" },
                {"French Guiana", "GUF" },
                {"Guam", "GUM" },
                {"Guyana", "GUY" },
                {"Hong Kong, China", "HKG" },
                {"Heard Island and McDonald Isla", "HMD" },
                {"Honduras", "HND" },
                {"Croatia", "HRV" },
                {"Haiti", "HTI" },
                {"Hungary", "HUN" },
                {"Indonesia", "IDN" },
                {"India", "IND" },
                {"British Indian Ocean Ter.", "IOT" },
                {"Ireland", "IRL" },
                {"Iran, Islamic Rep.", "IRN" },
                {"Iraq", "IRQ" },
                {"Iceland", "ISL" },
                {"Israel", "ISR" },
                {"Italy", "ITA" },
                {"Jamaica", "JAM" },
                {"Jordan", "JOR" },
                {"Japan", "JPN" },
                {"Jhonston Island", "JTN" },
                {"Kazakhstan", "KAZ" },
                {"Kenya", "KEN" },
                {"Kyrgyz Republic", "KGZ" },
                {"Cambodia", "KHM" },
                {"Kiribati", "KIR" },
                {"Saint Kitts-Nevis-Anguilla-Aru", "KN1" },
                {"St. Kitts and Nevis", "KNA" },
                {"Korea, Rep.", "KOR" },
                {"Kosovo", "KSV" },
                {"Kuwait", "KWT" },
                {"Lao PDR", "LAO" },
                {"Lebanon", "LBN" },
                {"Liberia", "LBR" },
                {"Libya", "LBY" },
                {"St. Lucia", "LCA" },
                {"Liechtenstein", "LIE" },
                {"Sri Lanka", "LKA" },
                {"Lesotho", "LSO" },
                {"Lithuania", "LTU" },
                {"Luxembourg", "LUX" },
                {"Latvia", "LVA" },
                {"Macao", "MAC" },
                {"Morocco", "MAR" },
                {"Monaco", "MCO" },
                {"Moldova", "MDA" },
                {"Madagascar", "MDG" },
                {"Maldives", "MDV" },
                {"Mexico", "MEX" },
                {"Marshall Islands", "MHL" },
                {"Midway Islands", "MID" },
                {"Macedonia, FYR", "MKD" },
                {"Mali", "MLI" },
                {"Malta", "MLT" },
                {"Myanmar", "MNR" },
                {"Mongolia", "MNG" },
                {"Northern Mariana Islands", "MNP" },
                {"Montenegro", "MNT" },
                {"Mozambique", "MOZ" },
                {"Mauritania", "MRT" },
                {"Montserrat", "MSR" },
                {"Martinique", "MTQ" },
                {"Mauritius", "MUS" },
                {"Malawi", "MWI" },
                {"Malaysia", "MYS" },
                {"Mayotte", "MYT" },
                {"Namibia", "NAM" },
                {"New Caledonia", "NCL" },
                {"Niger", "NER" },
                {"Norfolk Island", "NFK" },
                {"Nigeria", "NGA" },
                {"Nicaragua", "NIC" },
                {"Niue", "NIU" },
                {"Netherlands", "NLD" },
                {"Norway", "NOR" },
                {"Nepal", "NPL" },
                {"Nauru", "NRU" },
                {"Neutral Zone", "NZE" },
                {"New Zealand", "NZL" },
                {"Oman", "OMN" },
                {"Pakistan", "PAK" },
                {"Panama", "PAN" },
                {"Pacific Islands", "PCE" },
                {"Pitcairn", "PCN" },
                {"Fm Panama Cz", "PCZ" },
                {"Peru", "PER" },
                {"Philippines", "PHL" },
                {"Palau", "PLW" },
                {"Pen Malaysia", "PMY" },
                {"Papua New Guinea", "PNG" },
                {"Poland", "POL" },
                {"Puerto Rico", "PRI" },
                {"Korea, Dem. Rep.", "PRK" },
                {"Portugal", "PRT" },
                {"Paraguay", "PRY" },
                {"Occ.Pal.Terr", "PSE" },
                {"French Polynesia", "PYF" },
                {"Qatar", "QAT" },
                {"Reunion", "REU" },
                {"Romania", "ROM" },
                {"Russian Federation", "RUS" },
                {"Rwanda", "RWA" },
                {"Ryukyu Is", "RYU" },
                {"Saudi Arabia", "SAU" },
                {"Sabah", "SBH" },
                {"Sudan", "SDN" },
                {"Senegal", "SEN" },
                {"Yugoslavia", "SER" },
                {"Singapore", "SGP" },
                {"South Georgia and the South Sa", "SGS" },
                {"Saint Helena", "SHN" },
                {"SIKKIM", "SIK" },
                {"Svalbard and Jan Mayen Is", "SJM" },
                {"Solomon Islands", "SLB" },
                {"Sierra Leone", "SLE" },
                {"El Salvador", "SLV" },
                {"San Marino", "SMR" },
                {"Somalia", "SOM" },
                {"Special Categories", "SPE" },
                {"Saint Pierre and Miquelon", "SPM" },
                {"Sao Tome and Principe", "STP" },
                {"Suriname", "SUR" },
                {"Slovak Republic", "SVK" },
                {"Slovenia", "SVN" },
                {"Fm Vietnam Rp", "SVR" },
                {"Soviet Union", "SVU" },
                {"Sweden", "SWE" },
                {"Sarawak", "SWK" },
                {"Swaziland", "SWZ" },
                {"Seychelles", "SYC" },
                {"Syrian Arab Republic", "SYR" },
                {"Fm Tanganyik", "TAN" },
                {"Turks and Caicos Isl.", "TCA" },
                {"Chad", "TCD" },
                {"Togo", "TGO" },
                {"Thailand", "THA" },
                {"Tajikistan", "TJK" },
                {"Tokelau", "TKL" },
                {"Turkmenistan", "TKM" },
                {"East Timor", "TMP" },
                {"Tonga", "TON" },
                {"Trinidad and Tobago", "TTO" },
                {"Tunisia", "TUN" },
                {"Turkey", "TUR" },
                {"Tuvalu", "TUV" },
                {"Taiwan, China", "TWN" },
                {"Tanzania", "TZA" },
                {"Uganda", "UGA" },
                {"Ukraine", "UKR" },
                {"United States Minor Outlying I", "UMI" },
                {"Unspecified", "UNS" },
                {"Uruguay", "URY" },
                {"United States", "USA" },
                {"Us Msc.Pac.I", "USP" },
                {"Uzbekistan", "UZB" },
                {"Holy See", "VAT" },
                {"St. Vincent and the Grenadines", "VCT" },
                {"Fm Vietnam DR", "VDR" },
                {"Venezuela", "VEN" },
                {"British Virgin Islands", "VGB" },
                {"Virgin Islands (U.S.)", "VIR" },
                {"Vietnam", "VNM" },
                {"Vanuatu", "VUT" },
                {"Wake Island", "WAK" },
                {" World", "WLD" },
                {"Wallis and Futura Isl.", "WLF" },
                {"Samoa", "WSM" },
                {"Yemen Democratic", "YDR" },
                {"Yemen", "YEM" },
                {"Yugoslavia, FR (Serbia/Montene", "YUG" },
                {"South Africa", "ZAF" },
                {"Congo, Dem. Rep.", "ZAR" },
                {"Zambia", "ZMB" },
                {"Fm Zanz-Pemb", "ZPM" },
                {"Fm Rhod Nyas", "ZW1" },
                {"Zimbabwe", "ZWE" },
            };
            return param;
        }

        public static int GetStatusCode(string name)
        {
            Dictionary<string, int> param = new()
            {
                { "OK", 200 },
                {"Bad Request",400 },
                {"Unauthorized",401 },
                {"Forbidden",403 },
                {"Not Found",404 },
                {"Method Not Allowed",405 },
                {"Unsupported Media Type",415 },
                {"Server Error",500 },
                {"Bad Gateway",502 }
            };
            var result = param.Where(x => x.Key.Contains(name.ToString())).Select(x => x.Value).FirstOrDefault();
            return result;
        }
    }
}